### PR TITLE
Add package-lock.json

### PR DESCRIPTION
**Pull request by KoltesDigital**
*package-lock.json* is intended to be checked into source control.

### CODE REVIEW

**Comment by fand** [comment]
Thanks for PR!
btw I personally prefer yarn over npm because `packag-lock.json` bothered me several times... for example, package-lock.json sometimes changes when we just run `npm install`

**Comment by fand** [comment]
ah, I found the behavior might be changed.. gonna read this later  https://stackoverflow.com/questions/45022048/why-does-npm-install-rewrite-package-lock-json

**Comment by fand** [comment]
Today I ran into a problem caused by package-lock.json again on my day job, so I decided to continue using `yarn` for a while 😇 
I'll add instruction to use yarn to README.

Thank you for sending PRs!! 🙇 🙏

**Comment by KoltesDigital** [comment]
I never had a problem with it, but if you're good with yarn, stick with it!

**Comment by KoltesDigital** [comment]
Really? I'm interested in knowing about these case, if you are allowed.

**Comment by fand** [comment]
The first problem is that `package-lock.json` is updated when I just run `npm i`. At first it was intended but npm changed the behavior in newer versions..it's confusing.

The second problem, what I saw today, is a bit complicated...
When I run `npm i` I saw errors while installing some of dependencies in `package-lock.json` saying that they are not supported in node v10. But the packages are not installed when I use yarn instead of npm and I succeeded to install all dependencies. We decided to delete `package-lock.json` from the repository and regenerated it...

**Pull request closed without merging**
