### PR TITLE
Cap gamepad axis range

### PR DESCRIPTION
**Pull request by KoltesDigital**
Otherwise it wraps to 0 when axis is 1.

### CODE REVIEW

**Comment by fand** [comment]
thx for PR!
I didn't know that 256 is wrapped to 0 in Uint8Array😫

hmm, `Math.min(axis * 128 + 128, 255);` works well, but it's kind of hack.
It looks that `UnsignedByteType` is not suitable for representing axis data...
We should replace it with float texture because Gamepad API returns float values:
https://developer.mozilla.org/en-US/docs/Web/API/Gamepad/axes

It's a breaking change but is reasonable, IMO

**Comment by KoltesDigital** [comment]
Oh come on, your code tells you're an excellent coder!

I thought it was on purpose, because with floats it'll take four times the space in memory. 256 values is good enough for gamepad values.

**Comment by fand** [comment]
Currently the DataTexture takes 256 bytes (=256 * 1byte)
If we choodse float texture and use Float32Array, the array takes only 1KB (= 128 * 2 * 4bytes).
This difference is ignorable in modern PC.

**Comment by KoltesDigital** [comment]
Superseded by #24 .

**Pull request closed without merging**
