### PR TITLE
Add intspectrum

### PR DESCRIPTION
**Pull request by KoltesDigital**
This adds an integrated spectrum, useful for effects. However for the best effects, the FFT should almost not be smoothed, so `fftSmoothingTimeConstant` has to be overridden. Or another solution is to use a second analyzer with a fixed constant.

Sadly `package-lock.json` got into the commit, but it's a good idea to add it at some point anyway, so here it is.

### CODE REVIEW

**Comment by fand** [comment]
Thx @KoltesDigital !

However, I don't know if intspectrum is useful and how can it be used.
Could you show me some examples or ideas?

`intspectrum` can be achieved by using multipass rendering like this (though it's a bit complicated).
I can't tell it worth enough to add dedicated feature.

```glsl
/*{
  "audio": true,
  "PASSES": [{ "target": "intspectrum" }, {}]
}*/
precision mediump float;
uniform vec2 resolution;
uniform sampler2D spectrum;
uniform sampler2D intspectrum;
uniform int PASSINDEX;

void main() {
  vec2 uv = gl_FragCoord.xy / resolution;
  if (PASSINDEX == 1) {
    gl_FragColor += texture2D(spectrum, uv);  // Render to intspecturm
  }
  else {
    gl_FragColor = texture2D(intspectrum, uv);  // Render to canvas
  }
}
```

**Comment by KoltesDigital** [comment]
I agree this could be left outside of the core features if it fits in the multipasses. I was unsure whether WebGL allows reading and writing to the same buffer. But that way it is more customizable.

See https://github.com/KoltesDigital/veda/blob/6f14ed384b83c8f00def5a0a6b4fa80e6ad6d5f2/examples/audio_intspectrum.frag for a quick example. Whereas spectrum goes back to 0 after a beat, this gives the feeling on a progression with jolts on beats.

Then perhaps this shader should be given as an example, so to constitute a helper library for the users.

```
// Set this pass's target to intspectrum.
precision mediump float;
uniform vec2 resolution;
uniform sampler2D spectrum;
uniform sampler2D intspectrum;

void main() {
  vec2 uv = gl_FragCoord.xy / resolution;
  gl_FragColor = texture2D(spectrum, uv) + texture2D(intspectrum, uv);
}
```

**Comment by fand** [comment]
In multipass rendering we can write to a buffer on 1st pass and read it in other passes.
It's implemented by swapping 2 buffers like `backbuffer`.

I tried the sample and felt `intspectrum` is useful, but not simple enough to keep VEDA simple.
Maybe we'd better add features or documents to help users to use multipass rendering instead.

Anyways, thank you for contribution @KoltesDigital 😸  !

**Comment by KoltesDigital** [comment]
I understand the passes now, I agree that this feature could be left outside of the core thanks to passes!

**Pull request closed without merging**
